---
- hosts: ios
  gather_facts: false
  connection: local
    
  tasks:
    - name: GET VLAN
      ntc_show_command:
          connection: ssh
          platform: cisco_ios
          template_dir: /home/vv5347/ENG/ntc-ansible/ntc-templates/templates
          command: show vlan
          host: 10.91.109.24
          username: vv5347
          password: Oclo2hvr!
      register: vlan
      
    - debug: var=vlan